# Logitech F710 wireless controller
# Deadman (enable) button: Right Trigger
# D<>X button (located on the back panel) must be set to D
teleop:
  piloting:
    type: topic
    message_type: "geometry_msgs/Twist"
    topic_name: cmd_vel
    deadman_buttons: []
    axis_mappings:
      -
        axis: 4  # Right thumb stick (up/down)
        target: linear.x
        scale: 1.0
        offset: 0.0
      -
        axis: 3  # Right thumb stick (left/right)
        target: linear.y
        scale: 1.0
        offset: 0.0
      -
        axis: 1  # Left thumb stick (up/down)
        target: linear.z
        scale: 1.0
        offset: 0.0
      -
        axis: 0  # Left thumb stick (left/right)
        target: angular.z
        scale: 1.0
        offset: 0.0
  camera:
    type: topic
    message_type: "geometry_msgs/Twist"
    topic_name: camera_control
    deadman_buttons: []
    axis_mappings:
      -
        axis: 7  # Left D-Pad (up/down)
        target: angular.y
        scale: 83.0
        offset: 0.0
      -
        axis: 6  # Left D-Pad (left/right)
        target: angular.z
        scale: -35.0
        offset: 0.0
  takeoff:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: takeoff
    deadman_buttons: [5]  # R1
    axis_mappings: []
  land:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: land
    deadman_buttons: [7]  # R2
    axis_mappings: []
  emergency:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: reset
    deadman_buttons: [3] # Triangulo
    axis_mappings: []
  flattrim:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: activate_lqr_controller
    deadman_buttons: [0] # X
    axis_mappings: []
  flip:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: activate_lqr_controller
    deadman_buttons: [6, 0] # L2 + X
    axis_mappings: []
  snapshot:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: snapshot
    deadman_buttons: [4] # RT + LB
    axis_mappings: []
